### ISSUE TITLE
Numeric partitioning with add_partition() breaks idempotency

### ISSUE THREAD

**Issue by chumaltd** [ridgepole/ridgepole#388]
# Description

This is not my actual case, just for reporting.

* Middleware versions
  * Ridgepole 1.0.6
  * Ruby 3.0
  * Rails/Active Record 7.0.3
  * PostgreSQL 13.7

For example, the following Schemafile fails on the 2nd migration with PostgreSQL.

```ruby
create_table "counters", id: false, options: "PARTITION BY LIST (count)" do |t|
  t.bigint               "count"
end
add_partition("counters", :list, :count, partition_definitions: [{ name: "counters_1", values: { in: [1]}}])
```

On its 1st migration, it creates a partition as bellows:

```psql
rptest=# \d counters_1
            Table "public.counters_1"
 Column |  Type  | Collation | Nullable | Default
--------+--------+-----------+----------+---------
 count  | bigint |           |          |
Partition of: counters FOR VALUES IN ('1')
```

And on 2nd run, you'll get the following error:

```bash
Apply `Schemafile-counter`
[ERROR] All partition is different. please check partition settings.to:  {:type=>:list, :columns=>[:count], :partition_definitions=>[{:name=>"counters_1", :values=>{:in=>[1]}}]}, from: {:type=>:list, :columns=>[:count], :partition_definitions=>[{:name=>"counters_1", :values=>{:in=>["1"]}}]}
        /var/lib/gems/3.0.0/gems/ridgepole-1.0.6/lib/ridgepole/diff.rb:644:in `scan_partition_change'
```

`:in` from DB is recognized as string, which may follows quoted output from pg.
And if you quote parameters like following, it works as intended.

```ruby
create_table "counters", id: false, options: "PARTITION BY LIST (count)" do |t|
  t.bigint               "count"
end
add_partition("counters", :list, :count, partition_definitions: [{ name: "counters_1", values: { in: ['1']}}])
```
It looks a bit different from Ruby.  
This issue also applies to [sample Schema in README.md](https://github.com/ridgepole/ridgepole#partitioning), both of List Partitioning & Range Partitioning.

# Export

Exported after 1st migration:

```ruby
# Export Schema
create_table "counters", id: false, options: "PARTITION BY LIST(count)", force: :cascade do |t|
  t.bigint "count"
end

add_partition "counters", :list, [:count], partition_definitions: [{ name: "counters_1", values: {:in=>["1"]} }]
```

# Apply with `--verbose`

```bash
Apply `Schemafile-counter`
# Parse DSL
# Load tables
#   counters
# Compare definitions
#   counters
 {:definition=>{"count"=>{:options=>{}, :type=>:bigint}},
- :options=>{:id=>false, :options=>"PARTITION BY LIST(count)"},
+ :options=>{:id=>false, :options=>"PARTITION BY LIST (count)"},
  :partition=>
   {:columns=>[:count],
-   :partition_definitions=>[{:name=>"counters_1", :values=>{:in=>["1"]}}],
+   :partition_definitions=>[{:name=>"counters_1", :values=>{:in=>[1]}}],
    :type=>:list}}
# Table option changes are ignored on `counters`.
  from: {:options=>"PARTITION BY LIST(count)"}
    to: {:options=>"PARTITION BY LIST (count)"}

[ERROR] All partition is different. please check partition settings.to:  {:type=>:list, :columns=>[:count], :partition_definitions=>[{:name=>"counters_1", :values=>{:in=>[1]}}]}, from: {:type=>:list, :columns=>[:count], :partition_definitions=>[{:name=>"counters_1", :values=>{:in=>["1"]}}]}
        /var/lib/gems/3.0.0/gems/ridgepole-1.0.6/lib/ridgepole/diff.rb:644:in `scan_partition_change'
```

**Comment by chumaltd** [comment]
Relating to this issue, [the error message](https://github.com/ridgepole/ridgepole/blob/1.0/lib/ridgepole/diff.rb#L644) looks ambiguous.  

IMO, "Modifying partitions is not supported." is OK for safety.
But I'm not sure original intention.

**Comment by chumaltd** [comment]
Hi @winebarrel 
I agree there's no clear solution between Ruby and DBMS syntax diffs.
This issue cannot be the final.

IMO on partitioning, we always need an escape hatch for manual operations.
Some of changing partitioning logic requires direct data manupilation like `INSERT` after temporal detach.

Now, we have implicit skip-migration-mode with no `add_partition` Schemafile.
It's just safe.
This behavior should be stabilized as a spec, IMO.

Current `add_partition` looks yet convenient for long lived simple configurations.
This may apply for some LIST or HASH suitable apps.

Thanks.
