### ISSUE TITLE
Error when modifying generated columns

### ISSUE THREAD

**Issue by mkusaka** [ridgepole/ridgepole#482]
# Description
First, Thank you for the wonderful gem :)

I encountered an error while attempting to modify a generated column in a MySQL database using Ridgepole. Below, I detail the steps to reproduce the issue, the encountered error, and the environment in which the error occurs.

1. Install `ridgepole` and `mysql2`, and prepare a MySQL database.
2. Configure `database.yml` as follows:

```yaml
development:
  adapter: mysql2
  encoding: utf8mb4
  database: ridgepole_development
  host: 127.0.0.1
  username: root
  password: password
```

3. Apply the initial schema using this `Schemafile`:

```rb
create_table "users", id: :integer, force: :cascade, collation: "utf8mb4_0900_ai_ci" do |t|
  t.string "last_name", null: false
  t.string "first_name", null: false
  t.virtual "full_name", type: :string, as: "concat(`last_name`,_utf8mb4' ',`first_name`)", stored: true
end
```

Command:
```bash
ridgepole --config database.yml --apply --file Schemafile
```
This step completes successfully.

4. Modify the `Schemafile` to reverse the order of `first_name` and `last_name` in the full_name column:

```rb
create_table "users", id: :integer, force: :cascade, collation: "utf8mb4_0900_ai_ci" do |t|
  t.string "last_name", null: false
  t.string "first_name", null: false
  t.virtual "full_name", type: :string, as: "concat(`first_name`,_utf8mb4' ',`last_name`)", stored: true
end
```

Command:
```
ridgepole --config config/database.yml --apply --file Schemafile
```

5. Encounter the following error:

```
Apply `Schemafile.after`
-- change_column("users", "full_name", :virtual, {:type=>:string, :as=>"concat(`first_name`,_utf8mb4' ',`last_name`)", :stored=>true, :null=>true, :default=>nil, :unsigned=>false, :comment=>nil})
[ERROR] Mysql2::Error: Incorrect usage of DEFAULT and generated column
* 1: change_column("users", "full_name", :virtual, **{:type=>:string, :as=>"concat(`first_name`,_utf8mb4' ',`last_name`)", :stored=>true, :null=>true, :default=>nil, :unsigned=>false, :comment=>nil})
    /path/to/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query'
```

## Additional Information

A reproduction repository is available here for further reference: [ridgepole-generated-columns-issue-repro](https://github.com/mkusaka/ridgepole-generated-columns-issue-repro).

# Schemafile

## First apply
```rb
create_table "users", id: :integer, force: :cascade, collation: "utf8mb4_0900_ai_ci" do |t|
  t.string "last_name", null: false
  t.string "first_name", null: false
  t.virtual "full_name", type: :string, as: "concat(`last_name`,_utf8mb4' ',`first_name`)", stored: true
end
```

## Second apply

```rb
create_table "users", id: :integer, force: :cascade, collation: "utf8mb4_0900_ai_ci" do |t|
  t.string "last_name", null: false
  t.string "first_name", null: false
  t.virtual "full_name", type: :string, as: "concat(`first_name`,_utf8mb4' ',`last_name`)", stored: true
end
```

# DDL
## First apply (with dry-run)
```sql
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `last_name` varchar(255) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `full_name` varchar(255) AS (concat( `last_name`, _utf8mb4' ', `first_name`)) STORED
)
COLLATE=utf8mb4_0900_ai_ci
```

## Second apply (with dry-run)
```sql
ALTER TABLE `users` CHANGE `full_name` `full_name` varchar(255) AS (
  concat( `first_name`, _utf8mb4' ', `last_name`)
) STORED DEFAULT NULL
```

# Export

## After first apply
```rb
# Export Schema
# Load tables
#   users
create_table "users", id: :integer, charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
  t.string "last_name", null: false
  t.string "first_name", null: false
  t.virtual "full_name", type: :string, as: "concat(`last_name`,_utf8mb4' ',`first_name`)", stored: true
end
```

# Apply with `--verbose`
## First apply
```
Apply `Schemafile`
# Parse DSL
# Load tables
# Compare definitions
# Update schema
-- create_table("users", {:id=>:integer, :collation=>"utf8mb4_0900_ai_ci"})
   -> 0.0269s
```

## Second apply
```
Apply `Schemafile.after`
# Parse DSL
# Load tables
#   users
# Compare definitions
#   users
   {"first_name"=>{:options=>{:null=>false}, :type=>:string},
    "full_name"=>
     {:options=>
-      {:as=>"concat(`last_name`,_utf8mb4' ',`first_name`)",
+      {:as=>"concat(`first_name`,_utf8mb4' ',`last_name`)",
        :stored=>true,
        :type=>:string},
      :type=>:virtual},
    "last_name"=>{:options=>{:null=>false}, :type=>:string}},
- :options=>
-  {:charset=>"utf8mb4", :collation=>"utf8mb4_0900_ai_ci", :id=>:integer}}
+ :options=>{:collation=>"utf8mb4_0900_ai_ci", :id=>:integer}}
# Table option changes are ignored on `users`.
  from: {:charset=>"utf8mb4"}
    to: {}

# Update schema
-- change_column("users", "full_name", :virtual, {:type=>:string, :as=>"concat(`first_name`,_utf8mb4' ',`last_name`)", :stored=>true, :null=>true, :default=>nil, :unsigned=>false, :comment=>nil})
[ERROR] Mysql2::Error: Incorrect usage of DEFAULT and generated column
* 1: change_column("users", "full_name", :virtual, **{:type=>:string, :as=>"concat(`first_name`,_utf8mb4' ',`last_name`)", :stored=>true, :null=>true, :default=>nil, :unsigned=>false, :comment=>nil})
	/Users/name/src/github.com/mkusaka/ridgepole-generated-columns-issue-repro/vendor/bundle/ruby/3.3.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query'
```

# Expected Behavior
The DDL for the second apply seems to have an incorrect inclusion of DEFAULT NULL for a stored generated column, which appears to cause the error:

```sql
ALTER TABLE `users` CHANGE `full_name` `full_name` varchar(255) AS (
  concat( `first_name`, _utf8mb4' ', `last_name`)
) STORED DEFAULT NULL
```

When executing the following corrected DDL directly in the MySQL client, it results in the expected behavior without errors:

```sql
ALTER TABLE `users` CHANGE `full_name` `full_name` varchar(255) AS (
  concat( `first_name`, _utf8mb4' ', `last_name`)
) STORED;
```

This observation suggests that Ridgepole may be handling the DEFAULT clause incorrectly when modifying stored generated columns.

**Comment by winebarrel** [comment]
Can you tell me the version below?

* Ridgepole
* Ruby
* Rails/Active Record
* MySQL/PostgreSQL

**Comment by mkusaka** [comment]
@winebarrel 

Oops, sorry for not including my environment info earlier! Here it is:

* Ridgepole: 2.0.3
* mysql2: 0.5.6
* Ruby: 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
* Rails/Active Record: 7.1.3.2
* MySQL: 8.0.36

Also, you can check out the reproduction repository here: [ridgepole-generated-columns-issue-repro](https://github.com/mkusaka/ridgepole-generated-columns-issue-repro).

Thanks!

**Comment by winebarrel** [comment]
This is an ActiveRecord issue and will take some time to fix.
